---
- hosts: R3
  tasks:
    - name: Configuracion de interface R3-e0/1
      ios_config:
        parents: "interface e0/1"
        lines:
          - ip add 5.5.5.5 255.255.255.252
          - no shut
          - exit
    - name: Configuracion de interface R3-e0/0
      ios_config:
        parents: "interface e0/0"
        lines:
          - ip add 5.5.5.13 255.255.255.252
          - no shut
          - exit
    - name: Configuracion de interface R3-s1/0
      ios_config:
        parents: "interface s1/0"
        lines:
          - ip add 5.5.5.2 255.255.255.252
          - no shut
          - exit

- hosts: R4
  tasks:
    - name: Configuracion de interface R4-e0/0
      ios_config:
        parents: "interface e0/0"
        lines:
          - ip add 5.5.5.6 255.255.255.252
          - no shut
          - exit
    - name: Configuracion de interface R4-e0/1
      ios_config:
        parents: "interface e0/1"
        lines:
          - ip add 5.5.5.9 255.255.255.252
          - no shut
          - exit
- hosts: R5
  tasks:
    - name: Configuracion de interface R5-e0/1
      ios_config:
        parents: "interface e0/1"
        lines:
          - ip add 5.5.5.10 255.255.255.252
          - no shut
          - exit
    - name: Configuracion de interface R5-e0/0
      ios_config:
        parents: "interface e0/0"
        lines:
          - ip add 5.5.5.18 255.255.255.252
          - no shut
          - exit
    - name: Configuracion de interface R5-s1/0
      ios_config:
        parents: "interface s1/0"
        lines:
          - ip add 5.5.5.21 255.255.255.252
          - no shut
          - exit
- hosts: R2
  tasks:
    - name: Configuracion de interface R2-e0/1
      ios_config:
        parents: "interface e0/1"
        lines:
          - ip add 5.5.5.17 255.255.255.252
          - no shut
          - exit
    - name: Configuracion de interface R2-e0/0
      ios_config:
        parents: "interface e0/0"
        lines:
          - ip add 5.5.5.14 255.255.255.252
          - no shut
          - exit
   
- hosts: ISP
  tasks:
    - name: Configuración de OSPF-5 AREA-0
      ios_config:
        parents: "router ospf 5"
        lines:
          - network 0.0.0.0 0.0.0.0 area 0

- hosts: ISP
  tasks:
    - name: Grabar configuraciones
      ios_config:
        lines:
          - do wr